### ISSUE TITLE
Quarrier just doesn't do or request anything

### ISSUE THREAD

**Issue by smellbig** [ldtteam/minecolonies#11045]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [x] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [x] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [x] Single Player
- [ ] Multi Player

### Minecraft Version

1.21

### MineColonies Version

1.1.1055-1.21.1-snapshot

### Structurize Version

1.0.780-1.21.1-snapshot

### Current Behavior

my quarrier is just not starting and not requesting anything. i've fired/paused/restarted/rehired him multiple times, he's assigned to a quarry, and he just won't do anything. he's got tools, torches, everything.

<img width="871" height="346" alt="Image" src="https://github.com/user-attachments/assets/2a9ff4f7-f0a8-4ec5-9916-126f294befa6" /> 

<img width="686" height="732" alt="Image" src="https://github.com/user-attachments/assets/6455782d-dc27-48eb-880c-0ca7e32acf05" /> 

<img width="808" height="796" alt="Image" src="https://github.com/user-attachments/assets/5249b3d1-8c45-4e8e-93be-2f3c626a49cf" />

the only thing that might be relevant is the fact that the associated mine is requesting 22k+ torches and rails each: 

<img width="765" height="682" alt="Image" src="https://github.com/user-attachments/assets/e026d98a-9ab7-4d16-8bd7-3c7704d3ce5a" />

### Expected Behavior

i expect him to quarry

### Reproduction Steps

not really sure - just placed and constructed the quarry with my builder then assigned the quarrier via the mine.

### Logs

https://gist.github.com/smellbig/2ff933c280c58d63a0bacba6d7bf2bc4

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
Oh, just to check one thing I forgot to ask on discord, that material list in the mine, is that a static number, or is it counting up and then going down and counting up again?

**Comment by smellbig** [comment]
> Oh, just to check one thing I forgot to ask on discord, that material list in the mine, is that a static number, or is it counting up and then going down and counting up again?

the latter - it counts up and down.

**Comment by Jackman3323** [comment]
I have reproduced this on multiple versions, in singleplayer and multiplayer.

**Comment by ykretzcode** [comment]
I have approximately the same issue, quarry not working and the miner saying he finished his work. 

I saw you already solved the problem in July 2024 : https://github.com/ldtteam/minecolonies/issues/10026

I can add this for my game : 
When the miner us working and I have the builder goggles I can see the quarry being in a blue box deep in the ground. But at a moment the box disappears and miner stops working and tells he finished. I tried to remove quarry hut, place it at the same place and the miner restarted, and then few minutes later stopped again

**Comment by uecasm** [comment]
The quarrier can get a bit confused when you hire them into a mine that has already been building mineshafts.  It's best to build a new mine hut and hire the quarrier there instead.  Some styles even have a dedicated "quarrier" mine that doesn't even have a mineshaft space.

**Comment by Jackman3323** [comment]
I've tried a new normal mine to hire the quarter and I've tried an existing mine. I even tried one of the quarrier specific ones from a different style pack. No change. Is there any hope this gets fixed? I'm really tired of farming cobblestone and diorite manually despite having two mines...

**Comment by Raycoms** [comment]
fix pushed

**Comment by Jackman3323** [comment]
Same behavior, requesting ever increasing numbers of torches and rails while just standing at the quarry block.

**Comment by Raycoms** [comment]
Can you do an mc colony export for the colony with this quarry?

-------- Original Message --------

**Comment by Jackman3323** [comment]
[colony1Export.zip](https://github.com/user-attachments/files/22188965/colony1Export.zip) here's that colony export! Sorry for the delay, was moving :)

**Comment by Jackman3323** [comment]
This is still happening for me (despite full updates). I deleted the quarry block, crafted a new one, placed it, had the builder finish it, and tried to assign a new worker. But the same problem reared its head again. Here's an updated zip!

[colony1Export.zip](https://github.com/user-attachments/files/25322088/colony1Export.zip)

**Comment by Jackabm** [comment]
Im getting the same issue. How hasnt this been fixed? I see other reports of this same problem from years ago. Thats why the mine and quarry shouldnt be connected.

**Comment by Talyda** [comment]
> Im getting the same issue. How hasnt this been fixed? I see other reports of this same problem from years ago. Thats why the mine and quarry shouldnt be connected.

It was fixed. There might be a different problem now, and if you are experiencing one, it's a good idea to make a new issue, not comment on an old one that has been closed. Though in this case you probably don't need to, as they are aware that something broke.

**Comment by Jackabm** [comment]
Okay. It wasn't noted it was fixed here from what I can see. Will this auto apply to curseforge once the new fix is applied? As im using the industrial village modpack which includes minecolonies.

**Comment by cameronred82-jpg** [comment]
Make sure the quarrier can reach the bottom floor using the ladders. that the only way it can start. this fix the problem i was having,
