### ISSUE TITLE
Vanishing Colonists

### ISSUE THREAD

**Issue by KyleSolo** [ldtteam/minecolonies#2421]
### Minecolonies version

All the Mods 3 server, minecolonies version 1.12.2-0.8.8133

### Expected behavior

Colonists are visible.

### Actual behaviour

Colonists never appear, though the interface tells me my colony has 4/4. I can see in the town hall interface that they all have names.

Clicking the Recall Villagers button causes a colonist with a name above their head to appear next to the town hall block, but for only for a tiny fraction of a second.   They vanish almost instantly.

This has never worked on our server.

### Steps to reproduce the problem

Not sure how to reproduce.  I wonder if it is related to #2411, as they are also on All The Mods 3.
The server log had "Citizen has gone awol, respawning them" each time I clicked the Recall Villagers button.
The respawn command said something about "has been removed" each time I used it.

### Things I've tried with no effect:
Updating clients and the server to 1.12.2-0.8.8147
Deleting the minecolony folder in "world" in the hopes that this would "reset" minecolony and fix the issue.
Deleting the colony using console commands and making a new colony.
Having another player try to make a colony.
Using the kill and respawn citizen console commands.  I think the respawn command made the colonist appear for a split second by the town hall similarly to the Recall button but I don't remember for sure.

### Things I tried that "fixed" the problem:
Starting a singleplayer superflat world with ATM 3 + updated minecolony version 1.12.2-0.8.8147 and making a colony.  Several colonists appeared shortly after building the town hall.

So it worked in singleplayer, which makes me think something about our server is messed up... I could try making a new server but I'm interested in ways of fixing the existing server, since we've already been playing on it a while.  I'm also worried if I delete the existing server and make a new one that the issue will reoccur.

I am happy to troubleshoot further or even to dig around in the code if someone will point me in the right direction.  This seems like a really cool mod.

**Comment by PoroUsedSnax** [comment]
For the server, are you using an 'overworld' world? Things like the nether, end, or other modded worlds will not work (Worlds like BOP and such will though) it has to be a normal world that you would start in, like you had in single player with the superflat

**Comment by KyleSolo** [comment]
It's a Biomes O Plenty overworld in the All The Mods 3 server. The singleplayer test world was superflat.

Update:
/mc citizens info colony: 1 citizen: 1
Prints the name and id, then "Citizen entity not loaded" (same for all 4 citizens)

**Comment by WPaul15** [comment]
I can confirm that this also occurs on MineColonies Version 1.12.2-0.8.8160 in Single-Player.

**Comment by Raycoms** [comment]
Should be fixed

**Comment by Turbotowns** [comment]
It's bugged for me too. And the modpack is updated. Only two of my citizens are "loaded", while the first two are gone. And I can't change the assigned builder(my first citizen, one of the two that are gone) to one the ones that are still here.

**Comment by Throwaway12323** [comment]
I figured it out by accident, either do the command "/mc raid-now" or "/mc raid-tonight" after you fight them off your colonists will come back from the void

**Comment by jaeggr** [comment]
> I figured it out by accident, either do the command "/mc raid-now" or "/mc raid-tonight" after you fight them off your colonists will come back from the void

Doesn't seem to work now unfortunately, and bug is still present all these years (or reintroduced by another cause). `mc citizen reload <col ID> <citizen ID>` also doesn't work.

**Comment by Thodor12** [comment]
> > I figured it out by accident, either do the command "/mc raid-now" or "/mc raid-tonight" after you fight them off your colonists will come back from the void
> 
> Doesn't seem to work now unfortunately, and bug is still present all these years (or reintroduced by another cause). `mc citizen reload <col ID> <citizen ID>` also doesn't work.

Please do not bump issues from 5 years old on a version that is long unsupported by now. If you have this issue in a currently supported version please open a new issue.
