### ISSUE TITLE
[Edited By Orion:] Inventories are returning null as IItemHandler capability, even though they should not be since their hasCapability method is returning true.

### ISSUE THREAD

**Issue by Krovski** [ldtteam/minecolonies#3665]
### Minecolonies version
<minecolonies-1.12.2-0.10.256-BETA-universal.jar>

Version: 
	minecraft forge-14.23.5.2825, all the mods 3 remix downloaded from the twitch launcher, version 1.3.0, minecraft version 1.12.2, last updated 4 June 2019

### Expected behavior
No crashes :D

### Actual behaviour
- <I fulfilled one of the builder's requirements instead of allowing the request system to provide the necessary building materials for one of the buildings.  Immediately, the game crashed. I used MC edit to move my player out of the loaded area and no crashes, however, upon returning back to the colony, the game froze and caused a crash.  My assumption, based on the detailed crash report, is this crash has something to do with the programming of the request system.  Unfortunately I cannot get close enough to cancel a build without the game freezing or try any other diagnostic tests.>

<https://pastebin.com/sqVC4VjW>

### Steps to reproduce the problem
<Not sure if this is reproduce-able.  The detailed walk-through is in the paste bin link above.  Maybe some of the code may make sense?  Any assistance is greatly appreciated!>

1. 
2. 
3. 
4. ... Profit

# EDIT BY ORION:
This is not an RS bug, it has Nothing todo with the RS AT ALL!.
The crashlog explicitly states that this happens when an external mod is querying our hut blocks IItemHandler, which are ILLEGALLY returning null.
As stated in my comment downbelow, i am not sure if the OP is running a BETA from before or  after this was fixed.

If this beta is older then the fix, then this is a noop and OP should update to the newest ALPHA to get the fix, or wait for a new BETA.
If this beta is newer then the fix, we need to check again if we fixed al those issues.

**Comment by Raycoms** [comment]
Can you check if this happens with the newest alpha too?

**Comment by marchermans** [comment]
@Raycoms This has Nothing todo with the request system he is postulating. Look at the crashlog, seems like some class called RadiationHelper, from nuclear craft is accessing our inventories, and the system seems to be throwing an NPE again on looping over the buildings inventories, probably some inventory is again returning null when the capability is asked.

I am not sure we fixed that after or before that BETA. It might be time for another one as soon as i patch up that RS bug.

**Comment by Asherslab** [comment]
oh i completely forgot about this
might be related: https://github.com/turbodiesel4598/NuclearCraft/issues/517

**Comment by Krovski** [comment]
Hello again.  I updated the mod to Alpha (minecolonies-1.12.2-0.10.291-ALPHA-universal.jar).  The issue still persists.  Same crash report generated.  

"
> oh i completely forgot about this
> might be related: [turbodiesel4598/NuclearCraft#517](https://github.com/turbodiesel4598/NuclearCraft/issues/517)
"

Asherslab's comment is completely spot on.  I read over that post and my issue is pretty much the same.  I believe I was upgrading something to level 4 or 5 but cannot remember the style of the building.  I'm new to posting issues; my apologies for doubling the bugs/issues queue.

**Comment by marchermans** [comment]
@Raycoms

**Comment by Raycoms** [comment]
I checked through this several times and I still believe strongly that this issue is not on our side. One of the mods in the pack which you have in the warehouse crash on the hashSet calculation.
Every inventory which crashes on that has a bug. I will close this for now, hoping that NuclearCraft responds.

In the meanwhile, do you have any other modded inventories in the warehouse?

**Comment by Krovski** [comment]
@raycoms good morning. I believe there are blocks and items from other mods within the warehouse in the minecolonies racks. As far as chests or storage blocks being utilized from other mods, no.  I have some storage blocks outside the warehouse, but not within the boundaries set forth by minecolonies.   I’ll keep watching the other thread for updates and try to ping the other mod authors, too.  I just don’t want to have to start another map.... :(

**Comment by Raycoms** [comment]
Inside the storage doesn't affect it because we don't check for backpacks
yet. But within the warehouse range, especially connected to the racks or
warehouse block should affect it. The problem is that we cause the crash,
but what crashes are not our inventories. (We call some API of the
inventories which this particular inventory has a bug in).

Am Mi., 19. Juni 2019 um 20:26 Uhr schrieb Krovski <notifications@github.com

**Comment by someaddons** [comment]
you should be able to keep playing your world though, just set 
`    # Set this to true to remove any TileEntity that throws an error in its update method instead of closing the server and reporting a crash log. BE WARNED THIS COULD SCREW UP EVERYTHING USE SPARINGLY WE ARE NOT RESPONSIBLE FOR DAMAGES.
    B:removeErroringTileEntities=false`

in the forge.cfg to true and start up, it will then remove those tileentities causing the crash
