### ISSUE TITLE
City hall says Unemployed: -1 and lists 2 Knights while I only have 1.

### ISSUE THREAD

**Issue by MizzzManon** [ldtteam/minecolonies#6154]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2-forge-31.2.46
- MineColonies Version: minecolonies-0.13.464-BETA-universal
- Structurize Version: structurize-0.13.94-ALPHA-universal

## Problem description
In the City Hall it says i have -1 Unemployed citizens, and have 2 Knights employed. I only have 2 Guard towers but only 1 lists an employee. 

### Notes or related things
If I fire another worker so that it becomes unemployed, the City Hall will list 0 unemployed citizens.
I have tried to repair the Guard tower, and tore it down. This did not fix the issue and the City Hall kept listing 2 knights.
I have added pictures of both the guard tower window and the city hall window.
If needed I can provide the save before and after I tried the above changes.
I am playing minecolonies through the Valhelsia 2 modpack installed through twitch, and only manually added the FallingTree-1.15.2-2.4.0 mod and updated the minecolonies mod that came with the pack to the version listed above.

![minecolonies tower window](https://user-images.githubusercontent.com/37438203/100262905-18cce300-2f4d-11eb-9b12-f24731aa1728.png)

![minecolonies city hall info window](https://user-images.githubusercontent.com/37438203/100262907-19657980-2f4d-11eb-972f-949a6836667b.png)

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
fixed in latest alpha

**Comment by MizzzManon** [comment]
ok so i'm a bit confused now... where would i download the latest alpha for minecraft 1.15.2? or do i just use the same file as for 1.16.4? i downloaded the minecolonies official pack through twitch, do i just copy over the minecolonies-0.13.458-ALPHA-universal file and delete the minecolonies-0.13.464-BETA-universal or should i copy over every single mod file in that instance? I would prefer to keep playing through the valhelsia modpack.

**Comment by ravenbuilder934** [comment]
Delete the beta file and replace it with https://www.curseforge.com/minecraft/mc-mods/minecolonies/files/3120026

**Comment by MizzzManon** [comment]
It looks like the new file did not fix the issue, i still have the city hall telling me i have 2 knights and the 2nd guard tower has no worker assigned and 10/11 citizens.
