### ISSUE TITLE
2nd Warehouse not used by all couriers when 1st is full

### ISSUE THREAD

**Issue by smmmadden** [ldtteam/minecolonies#6284]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: 0.13.525-ALPHA
- Structurize Version: 0.13.104-ALPHA
- Related Mods and their Versions: n/a

## Expected behavior

if the setting to support multiple warehouses is enabled, it shouldn't matter if one is full.  The chat shouldn't be filling up with warehouse is full messages but instead, the couriers should know there is a second warehouse to deliver to.  If the first warehouse frees space from other deliveries, then either warehouse would be fair game.
## Actual behavior

When the first warehouse is full (expanded 5 times) and is full, the couriers report that the warehouse is full repeatedly in chat, until I remove something myself and bring it to warehouse 2.  I've set limittoonewarehousepercolony=false and have couriers next to each warehouse.  

## Steps to reproduce the issue

1.  set the limittoonewarehousepercolony=false
2.  restart server
3.  create second warehouse and let the first one get full.  Messages will flood the chat window until it is resolved.

### Logs

Nothing in logs showing the repeated chat warnings but it never stops.
- latest.log:   https://pastebin.com/HRsYP8ZK
- crashlog:  n/a

### Notes

![image](https://user-images.githubusercontent.com/10309346/102844090-b0044980-43d8-11eb-9416-bb1156fc55e6.png)
There are a lot of ...server overloaded messages in logs which I need to address separate from this issue.
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Couriers are PER warehouse. Each courier is assigned to one warehouse and can't handle others. This is intended.

**Comment by smmmadden** [comment]
Thanks, then that means multiple warehouses are really not supported.  If warehouse 1 is full and I fire the couriers that have been using this warehouse, then no one would be picking up/delivering to that full warehouse.  Adding a second warehouse would work for new couriers  but all that inventory in the first should not be ignored or would it make sense to move resources to the new warehouse.  Nor should the chat be filled with non-stop repeated messages that the warehouse is full.  Once or twice is fine, but it shouldn't stay in that endless loop.
The simplest approach (which may not be for coding it), would be to allow it to be upgraded more than 5 times or allow more levels (up) that could provide near infinite resource space.  I'm open for other suggestions on how to correct this if you can think of what that might be.  Thanks!!

**Comment by Raycoms** [comment]
1) you should get additional couriers for the new warehouse
2) you should probably move some things over to the new warehouse

**Comment by smmmadden** [comment]
possibly, but there is a bug in the endless loop of messages stating the warehouse is full.  At the least that should be fixed.

The second warehouse has a courier and that one is working but that worker doesn't check the other warehouse.  It sounds like multiple warehouses should just not be supported given that it would require a lot of recoding to cover all the variables like warehouse 1 has 3 couriers and warehouse 2 has 1 courier and there doesn't appear to be a way to tell any of the couriers to check warehouse 1 first before going to warehouse 2 before picking up or dropping off.

**Comment by Raycoms** [comment]
We used this nicely. Just make sure none of the warehouses is completely full and the system runs perfectly fine.

**Comment by Raycoms** [comment]
(as long as there is at least one courier in each warehouse)

**Comment by CAIHUDD** [comment]
Nicely? same issue still happened recently when I'm playing minecolonies on 1.18.2. Since I built second warehouse, those product buildings built after the second warehouse only connect with the 2nd one.

So I had no choice but to destroy my first warehouse and picking all items up to the 2nd one, or it would be too far to use my first warehouse. However, surprisingly, all my deliverymen in the 2nd warehouse saying 'My AI has run into an issue'.

What should I do now? It is pretty obvious that one warehouse is totally not enough for a 200citizens colony.

**Comment by Talyda** [comment]
I think probably the sensible thing to do would be to start an issue for your problem, as it is very unlikely to be the same thing that was a problem 2 years ago.
