### ISSUE TITLE
Barracks 5 - Builder doesn't accept Rallying Banner

### ISSUE THREAD

**Issue by bonzai1102** [ldtteam/minecolonies#7449]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:
- MineColonies Version:
- Structurize Version:
- Related Mods and their Versions:

## Actual behavior
What actually happens when this feature is used in its current state?
The Builder doesn't take the Rallying Banner and can't finish the Building.
Tried this with a new crafted with and without attached Guards.
![Screenshot 2021-07-29 102132](https://user-images.githubusercontent.com/20872116/127458121-bb13d90e-1c54-4ac8-8ec6-532c58c2c41d.png)

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Oraxian** [comment]
Confirmed that this issue exists in the Asian Barracks 3 schematic as well.

**Comment by tecnobrat** [comment]
I'm still having this issue on `minecolonies-0.14.328-ALPHA-universal`. I had a Wooden Barracks at Level 4, and I had upgraded it to Level 5 before upgrading minecolonies and experienced this bug.

I have since upgraded and it still won't take the Rallying banner. I have cancelled the upgrade and tried upgrading again, same issue.

**Comment by Raycoms** [comment]
Yes, the schmatic has to be updated.

**Comment by tecnobrat** [comment]
What do I do to make that happen?

**Comment by March75** [comment]
This problem is also in fortress-barracks T3. Is there a workarround until this is fixed in a new version?

**Comment by uecasm** [comment]
At the moment, just place the banner manually.

**Comment by RC3764** [comment]
Well, where should I place it.. issue with Barracks 3.

btw. cant plaace this banner anywhere.. needs to be some kind of functionality

**Comment by MotionlessTrain** [comment]
It is usually placed in an item frame

**Comment by RC3764** [comment]
Unfortunately no item frames visible. Is there any website where pictures are shown?

Edit: Its the asian style...

**Comment by uecasm** [comment]
The builder won't place the item frame until they have the banner.  You would have to place both if you want to do it manually -- they usually go on the ground next to the barracks hut, but it may vary with different styles.  You can make a second barracks hut item and look at the preview to see exactly where it goes, though you'd need to be careful of rotation.

Having said that, this bug has been fixed now.  So upgrade to the latest version and give them a brand new rallying banner and it should just work.

**Comment by Alf007** [comment]
Tried with minecolonies-1.0.2-ALPHA-universal (latest version to date)
and still have the issue.

**Comment by RedStoner** [comment]
This is still an issue and not fixed!!!
minecolonies-1.0.0-RELEASE-universal
structurize-0.13.219-ALPHA-universal

**Comment by Premieress** [comment]
Can confirm still not fixed

**Comment by Talyda** [comment]
> Can confirm still not fixed

What version are you playing? They should all have been removed from schematic now I think

**Comment by Premieress** [comment]
version 1.16.5-1.0.503-BETA. Trying to do Barracks level 3

**Comment by MotionlessTrain** [comment]
It isn't removed from all styles, yet

What style are you using?

**Comment by Raycoms** [comment]
Doesn't have to be removed. Just a new one has to be put.

**Comment by Premieress** [comment]
I'm using birch. I also had an issue with the clock but found a very easy workaround for that one, this one no though

**Comment by Talyda** [comment]
> I'm using birch. I also had an issue with the clock but found a very easy workaround for that one, this one no though

Workaround for this one is to place them yourself =) Bring up a ghost of the building, see where they go and place them =)

**Comment by Premieress** [comment]
Ill have to do that after the server Im playing on updates to 3.5.1 then, since Im still on 3.5.0 atm and it crashes when I use the build tool lol

**Comment by Premieress** [comment]
Was able to place the item frame and the rally flag, didn't complete. Builder just stood in his hut saying he needs the banner still

**Comment by Talyda** [comment]
Cancel his requests.
BTW please use discord for further support like this =)

**Comment by Premieress** [comment]
Tried that already many times, will move to the discord

**Comment by bobhilbig** [comment]
I have found that giving the item directly doesnt work, but if a courier delivers the banner, the builder will accept it.

**Comment by Grimjahk** [comment]
Not sure if this helps... I was having the same problem and I noticed two things. 1) When I placed manually it did not work, 2) I right clicked the banner once and got the "click it on a tower first to make it work" message, (in my mind I thought it was like activating a blood magic orb, changing it's state) so, I tried giving it to the builder again and this time he took it and finished the build. BUT when he placed the frame and the banner, it was in a different spot from where I tried it. So, Manual may still work. (he placed different than the ghost of the barracks I used for reference)

**Comment by iopredman** [comment]
Since I don't see it mentioned here, as of 1.0.634 beta, asian barracks level 3 also had this issue.

**Comment by lebanni** [comment]
minecolonies-1.16.5-1.0.787-BETA, still happening in fortress barracks level 3.

**Comment by NoahConstrictor8** [comment]
Not sure what version, I assume the most recent, though I'm not the server owner so idk, but it's still happening in Stone Level 3

**Comment by NoahConstrictor8** [comment]
Really annoyed cause I like an idiot decided to break and then replace the barracks block. And now my builder is rebuilding from scratch. Levels 1 to 3 plus towers only took like 2 hours though cause my current builder is a g, so I guess I'll try other options if this doesn't work later.

**Comment by Talyda** [comment]
Just place the banner yourself when ti gets to that point again

**Comment by NoahConstrictor8** [comment]
The issue was I didn't know where to place it. And you cant pull up the barracks design on the build tool without a second barracks. Which I did not have. Nor did I have the iron to make a second one.

**Comment by Talyda** [comment]
It should show when you make the preview of the barracks pop up - just bring another preview close enough to make it pop up =)  Or go into a creative single player game =)  *probably* it is in an item frame on the floor in front of the hut block.

**Comment by Lunan** [comment]
Grimjahk earlier mentioned that he tried right clicking with the banner and get the "Sneak + right click..." message, and then he could hand it over. This is indeed true. 

Simply have the banner in your hand and right click anywhere so you get that message, after that the builder will accept it. It is as if the banner isn't "real" before you have tried using it.

**Comment by Elania21** [comment]
Minecraft Version: 1.19.2, All The Mods 8 v 1.0.18
    MineColonies Version: minecolonies-1.19.2-1.0.1391-BETA
    Structurize Version: ?

When I tried to give the banner to my builder (Dark Oak Treehouse theme), she did not accept it. I was able to "Shift + Right-Click" on the banner, and then the build interface accepted it.
