### ISSUE TITLE
Miner creating cobblestone hallways in mid air

### ISSUE THREAD

**Issue by SulpherStaer** [ldtteam/minecolonies#773]
### Minecolonies version

version 1.11-0.6.3282

### Expected behaviour

- When mining at level 0, the miner should stop mining when encountering open air areas, or at least not cover them with cobblestone.

alternative behaviour

- When mining, and encountering an area exposed to air, only build the floor of the mine (preferably wood, to simulate bridges of the naturally spawned mine shafts), do not put up walls or a ceiling.

### Actual behaviour

- The miner exited the mountain, and started building a cobblestone mine pathway across a shore / lake, into the water, instead of stopping.

alternate explanation of behaviour

- The miner encountered full airblocks where it wanted to mine. It then proceeded to build a full mine path out of cobblestone, hovering above the water.

### Steps to reproduce the problem

1. Build a colony
2. Build a miner ontop of a raised area near a shore
3. Have the miner mine at level 0
4. Observe strange behaviours when breaching the surface

**Comment by Raycoms** [comment]
That really depends imo.
IMO he should by any cost try to mine down and fill up air with cobblestone.

**Comment by SulpherStaer** [comment]
I am not talking about the mineshaft itself... I'm talking about when it's branching out. When it is branching, it isn't going down. It's going sideways.

And, at level 0, going sideways, eventually will have you breach the surface if you are on a mountain, or hilly terrain.

I have already fixed the weird bit, but I should have made a screenshot. It looked extremely dumb, the floating cobblestone mine across the water.

**Comment by Raycoms** [comment]
Yeah that's still a problem to detect.
Maybe if 9*9 is water or air he shoudl break. But should he break on a ravine or tunnle or similar?

**Comment by SulpherStaer** [comment]
Ravines and tunnels are obviously different. Though I think, it would already be a very good fix that when there's air blocks above where he is mining, he should not put up cobble walls and ceilings, but only put down wood as a 'bridge'. (similar to how it happens in generated mineshafts crossing ravines)

I think, having the miner stop when encountering air or water would break him at lower depths. So, my suggestion would be to have it continue when exposed to the sky, but only use wood as a pathway, and skip building walls and ceilings. (still plonk the supports, as that just looks nice imo)

**Comment by Raycoms** [comment]
And when there is lava close and the wood will burn?

2017-04-06 15:16 GMT-03:00 sylcai <notifications@github.com>:

**Comment by SulpherStaer** [comment]
I didn't think about lava. I don't have a suggestion for that. I haven't seen the miner encounter lava yet either, so I do not know how it handles it at the moment.

**Comment by kedamono** [comment]
In case of Lava, use cobblestone.

**Comment by Raycoms** [comment]
problem is we would have to scan up to 3-5 blocks down to make sure nothing
will light on fire.

2017-04-07 15:08 GMT-03:00 kedamono <notifications@github.com>:

**Comment by SulpherStaer** [comment]
Lava only is a problem at certain levels when mining. Maybe have it not use wood to bridge when down a certain Y level. I mean, how does it detect lava now to not build supports?...

Not using wood below a certain Y is certainly cheaper than scanning for lava.

**Comment by Raycoms** [comment]
He just removes lava and stays far away and places the structure around to
avoid lava floating in =D

2017-04-07 15:11 GMT-03:00 sylcai <notifications@github.com>:

**Comment by marvin-bitterlich** [comment]
I am closing this for now as it mostly consists of discussion. Once we have a solution for the miner that is better then the "safest miner ever" we currently use, we can open an issue targeting that
