### ISSUE TITLE
Quarrier does nothing and AI Error

### ISSUE THREAD

**Issue by Shock-Volt** [ldtteam/minecolonies#8092]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-1.16.5-1.0.429-RELEASE

### Logs

- latest.log: [] (https://gist.github.com/Shock-Volt/ed1a7103cac387eb9a9eef51f8f7e0ab)

## Steps to reproduce the issue / details
I am having issues with quarry and quarrier. The quarry was built but the quarrier started breaking parts of it and was digging one block off. So i had the builder deconstruct it and then build it. Now the quarrier doesnt do anything stands still until the AI error comes up. Only pops up when they are assigned as a quarrier. Same result with different workers.

Just reporting the AI issue. 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Did you try fire/re-hire?

**Comment by Shock-Volt** [comment]
Yes. Even hired different person.

**Comment by Raycoms** [comment]
Basically, the problem is that the position they're trying to build at is outside of the range (because of the bad offset earlier). Hiring a miner (not quarried) at the building temporarily until they start building and then hiring a quarried should solve that.

**Comment by Shock-Volt** [comment]
But wouldn't deconstructing the building fix that issue? I have deconstructed and rebuilt it by the builder 2x. Also when you say hire miner do you mean for the mine or the quarry? Cause you cant for quarry, so i assume for mine. I rebuilt my quarry to do what you said but know my miner is broken and everytime he goes to mine his AI breaks. Fire and rehire with him or another citizen doesnt fix it.

**Comment by Raycoms** [comment]
The data is stored at the mine, so at the mine hire a normal Miner.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by Shock-Volt** [comment]
ok Well now when I hire a miner he gets he AI glitch too.

**Comment by Raycoms** [comment]
new log please

**Comment by Shock-Volt** [comment]
https://gist.github.com/Shock-Volt/17d4302d69b08299dec9dc830c39aa31

**Comment by Shock-Volt** [comment]
@Raycoms I new to this is there instructions on the fix? Am i supposed to put the script somewhere? Sorry and thank you!

**Comment by Raycoms** [comment]
new file will be uploaded to curse soon. Use that, fire/rehire the quarried at the quarry and it should be solved.

**Comment by Shock-Volt** [comment]
Will that be only for 1.18 or for 1.16.5 too, because I am playing that. Also Thank you for all your help! This is the first time I am using github and reporting bug.

**Comment by MotionlessTrain** [comment]
Both: 1.0.453 for 1.18.1 and 1.0.454 for 1.16.5

**Comment by Shock-Volt** [comment]
Thank you!

**Comment by MarobsKoco** [comment]
I also have a problem with the quarry, im on minecraft 1.18.2. forge 40.1.86 and i put my miner on the quarry, now i look at the required resources and he is counting what he needs. but at some point he start over again. like the framed cobbledtone double crossed and the torches, it counts up till cobble:446, torches: 39, then starts over with counting, its not even requesting them. i tried to rebuild it and even fire and rehire again, but nothing seems to work. Using the minecolonies-1.18.2-1.0.1130-ALPHA. how can i sovle this or is this something the developer has to solve?

**Comment by skiderz458** [comment]
having same issue in 1.19.2

**Comment by Raycoms** [comment]
@skiderz458 and @MarobsKoco please make a new issue also telling us which style, quarry rotation, etc
