### ISSUE TITLE
[BUG] Y axis of paintings increasing every time a schematic rotate

### ISSUE THREAD

**Issue by emanuele246gi** [ldtteam/minecolonies#8206]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [ ] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.16

### MineColonies Version

1.0.554

### Structurize Version

1.0.371

### Related Mods and their Versions

Forge: 36.2.33

### Current Behavior

![2022-03-31_12 35 19](https://user-images.githubusercontent.com/61762317/161037220-fee958d4-165a-4d19-b541-fe293610fc04.png)

### Expected Behavior

Paintings staying in the original y position

### Reproduction Steps

To see it in the preview, rotate a schematic with paintings in it and look for them, every time you rotate they will go up

### Logs

Too large

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Nightenom** [comment]
This was fixed for 1.18, not sure if there is way/will to backport it
Issue tracking progress for 1.18 ldtteam/structurize#426

**Comment by emanuele246gi** [comment]
Well I just made the issue here on Github as they said it to me on Discord

**Comment by Moobien** [comment]
I thought Sam fixed this a year ago

**Comment by Raycoms** [comment]
I checked and this is not a problem anymore. Althouigh painting placement isn't really perfect.

**Comment by emanuele246gi** [comment]
![2022-10-04_15 53 54](https://user-images.githubusercontent.com/61762317/193838256-c71699e6-72ef-486f-b314-779b2052b1f4.png)

Of course it's still a problem. The painting wasn't supposed to be attached to the roof, but a block below this position

**Comment by emanuele246gi** [comment]
Now I'm in the 1.18.2 version, with minecolonies-1.18.2-1.0.1048-BETA and with structurize-1.18.2-1.0.424-ALPHA

**Comment by emanuele246gi** [comment]
![2022-10-04_15 59 10](https://user-images.githubusercontent.com/61762317/193839493-ce8d4346-7b17-49b3-9367-d344fadbd232.png)
Look at this, how is the issue not there anymore?

**Comment by MotionlessTrain** [comment]
Could it be that the issue was only fixed in 1.19? (in which case, 1.18 will probably get the fixes later)

**Comment by emanuele246gi** [comment]
In that case I can wait, thanks for the answer!

**Comment by Raycoms** [comment]
okay, so the issue name is misleading. Actually, it offsets paintings by 1, but randomly. In 1.19 it is at most by 1, not with each rotation but rather based on the weird way images are processed

**Comment by uecasm** [comment]
I haven't looked at things recently, but in the past one issue was that it used the coordinate of the corner instead of the coordinate of the center (or vice versa), so it worked for 1x1 paintings but not for larger ones.

**Comment by Raycoms** [comment]
It seems to be related to the recalculation of the placement pós which derps

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by emanuele246gi** [comment]
Thank you guys, I really love your mod!
