### ISSUE TITLE
Leaf Dropping Bug

### ISSUE THREAD

**Issue by Normann92** [ldtteam/minecolonies#8507]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
I am also running the latest (possible) versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/). Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.0.887-BETA

### Structurize Version

1.0.411-ALPHA

### Related Mods and their Versions

Forge Version: 40.1.60
BlockUI Version: 0.0.55-ALPHA
Domum Ornamentum 1.0.50-ALPHA

### Current Behavior

Cutting down trees after entering my village results in the trees dropping leaf blocks.

### Expected Behavior

Leaves should drop sticks, saplings etc.

### Reproduction Steps

This was done on a server.

If I login far away from my Minecolonies village and chop trees down I will get the expected loot from the trees (sticks / saplings). If I however visit my village, the drops from the trees will change to leaf blocks. The trees will keep dropping leaf blocks even after leaving the village, and will even carry over into my singleplayer world if I were to go to that after the bug has begun.

Restarting the game will fix the issue, but it will come back the second I step foot in my village.

### Logs

Nothing shows up in the latest.log when the bug occurs

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
fixed int he latest

**Comment by MotionlessTrain** [comment]
Though they are on the latest version, so apparently it is still possible to get this bug

**Comment by Moobien** [comment]
They said it happened on 887 Beta

**Comment by Moobien** [comment]
Mcdorf just reported this issue happening again. please reopen as this bug is back.

**Comment by MotionlessTrain** [comment]
Mcdorf experienced it on 1.0.867
