### ISSUE TITLE
Deliveryman Bug

### ISSUE THREAD

**Issue by ghost** [ldtteam/minecolonies#964]
### Minecolonies version

minecolonies-universal-1.10.2-0.7.848

### Expected behavior

- Delivery person to deliver things from the warehouse to workers chests and the other way around

### Actual behaviour

- Delivery person fills chests with 0 amounts of items. For example, a cracked stone brick with a red zero has been placed in many of my chests and even when the chest has room the delivery person insists its too full and must be emptied.

### Steps to reproduce the problem

1. Make a town with no cheats on
2. Make some delivery people
3. Make some workers for them to deliver to and have them work for a while/put stuff in chests for them to move around and see what happens when delivery people reach worker chests for a few times
4. Profit/spam in chat saying they cant deliver

**Comment by wilsondgonzales** [comment]
@xDemonChip this has been fixed. update to at least ~0.7.930~ 0.8.930 (typo)

**Comment by ghost** [comment]
@wilsondgonzales I dont see it updated on curse or the repository, is it a beta release? Is there one for 1.10.2?

**Comment by Raycoms** [comment]
Its an alpha release

2017-05-09 18:33 GMT-03:00 xDemonChip <notifications@github.com>:

**Comment by nekatu** [comment]
Unfortunately Issue still present in 1.11.2 0.8.930 as per #947

**Comment by wilsondgonzales** [comment]
@nekatu @Raycoms I've verified that 

• deliverymen does deliver items from the warehouse
• deliverymen does take items from workers chests to the warehouse
• Workers do put items they've harvested to their worker chests

In short, any inventory related bugs seem to be eliminated. I'll have to verify the farmer as i previously had an instance where he was asking for seeds but the request was ignored

**Comment by marvin-bitterlich** [comment]
fixed
